name: 兰州大学定时健康打卡

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  # 每天3点、6点、8点、10点进行尝试打卡，注意要把北京时间转为UTC时间再填入下面
  # schedule:
  #   - cron: '0 0,2,19,22 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # 健康打卡
  lzu_auto_check:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # clone当前仓库，并切换到根目录
      - uses: actions/checkout@v3

      - name: '配置python环境'
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: '安装必要的python库'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: '健康打卡'
        env:
          CARDID: ${{ secrets.CARDID }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SENDKEY: ${{ secrets.SENDKEY }}
          TZ: Asia/Shanghai
        run: python lzu_auto_check.py
